version: "3"

services:
  web:
    container_name: web
    image: dangminhngo/crate-web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - crate_network
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crate_network

volumes:
  pgdata:
    driver: local

networks:
  crate_network:
    driver: bridge
